import type { CapabilityPluginManifest } from '../../../types/capability-registry.v1.js'

export const SCENIC_OVERLAY_PLUGINS: CapabilityPluginManifest[] = [
  {
    id: 'color_hint_square_overlay',
    label: 'Color Hint Square Overlay',
    status: 'verified',
    targetLayer: 'overlay',
    layerKind: 'overlay',
    atomicity: 'atomic',
    family: 'color_hint',
    primaryLayer: 'overlay',
    secondaryLayers: [],
    fallbackPreset: 'primitive_color_hint_overlay',
    capabilities: [
      'color hint overlay',
      'color square label',
      'swatch text cue',
      'color label disappears on unlock',
      '色块提示',
      '颜色方块',
      '汉字颜色提示',
    ],
    requiredParams: [],
    defaultParams: {
      square_size_pct: 5.4,
      fade_sec: 0.12,
    },
    compatibleLayers: ['mask_reveal', 'color_transform', 'audio_driver', 'texture_grade'],
    acceptedAssetTypes: ['image', 'video', 'generated_video', 'text'],
    negativeKeywords: ['watermark', 'subtitle paragraph', 'full frame grade', 'collage'],
    boundary: {
      supports: {
        'overlay.type': ['color_hint', 'swatch', 'short_label'],
        'overlay.content': ['text', 'color'],
        'sync.driver': ['audio_beat', 'manual'],
      },
      cannotSupport: ['geometry.layout=collage'],
      forbiddenLayers: ['layout', 'distortion'],
      requiresCompositionFor: ['mask_reveal', 'color_transform'],
      adaptability: {
        style: 'high',
        timing: 'high',
        geometry: 'medium',
        assets: 'high',
      },
    },
    description:
      'Small color swatch plus short label used before a scenic color unlock, then faded out on the trigger.',
  },
  {
    id: 'segment_fade_overlay',
    label: 'Segment Fade Overlay',
    status: 'verified',
    targetLayer: 'overlay',
    layerKind: 'overlay',
    atomicity: 'atomic',
    family: 'fade_overlay',
    primaryLayer: 'overlay',
    secondaryLayers: [],
    fallbackPreset: 'primitive_fade_overlay',
    capabilities: [
      'fade to black',
      'fade from black',
      'segment outro fade',
      'ending fade',
      '收尾淡黑',
      '淡入淡出',
    ],
    requiredParams: [],
    defaultParams: {
      color: '#000000',
      duration_sec: 0.45,
      direction: 'out',
    },
    compatibleLayers: ['texture_grade', 'audio_driver', 'color_transform', 'mask_reveal'],
    acceptedAssetTypes: ['image', 'video', 'generated_video'],
    negativeKeywords: ['color hint', 'watermark', 'collage layout'],
    boundary: {
      supports: {
        'transition.type': ['fade', 'fade_to_black', 'fade_from_black'],
        'timeline.position': ['segment_start', 'segment_end', 'outro'],
      },
      cannotSupport: ['geometry.layout=collage'],
      forbiddenLayers: ['layout'],
      requiresCompositionFor: [],
      adaptability: {
        style: 'medium',
        timing: 'high',
        geometry: 'high',
        assets: 'high',
      },
    },
    description:
      'Reusable fade overlay for scenic montage section endings, openings, and final fade-to-black outros.',
  },
]
