export const TASK_STATUS = {
    QUEUED: 'QUEUED',
    ANALYZING: 'ANALYZING',
    WAITING_USER_EDIT: 'WAITING_USER_EDIT',
    GENERATING: 'GENERATING',
    CANCELLING: 'CANCELLING',
    CANCELLED: 'CANCELLED',
    COMPLETED: 'COMPLETED',
    FAILED: 'FAILED',
};
//# sourceMappingURL=pipeline.js.map