import type { RemotionTimelineSpecV1 } from '../../../shared/types/remotion-timeline-spec.v1'

export const fallbackTimelineProps: RemotionTimelineSpecV1 = {
  schema_version: 'remotion_timeline_spec.v1',
  task_id: 'timeline_preview',
  canvas: {
    width: 1080,
    height: 1920,
    fps: 30,
    duration_sec: 6,
    background: '#09090b',
  },
  assets: [],
  scenes: [
    {
      id: 'preview_card_001',
      type: 'remotion_card',
      start_sec: 0,
      duration_sec: 2,
      title: 'Remotion Timeline',
      subtitle: 'Scene 1',
      body: 'Programmatic scene composition',
      accent_color: '#38bdf8',
      visual_role: 'hook',
    },
    {
      id: 'preview_card_002',
      type: 'caption_scene',
      start_sec: 2,
      duration_sec: 2,
      title: 'TransitionSeries',
      subtitle: 'Scene 2',
      body: 'Transitions and overlays are rendered by Remotion.',
      accent_color: '#f59e0b',
      visual_role: 'feature',
    },
    {
      id: 'preview_card_003',
      type: 'data_viz',
      start_sec: 4,
      duration_sec: 2,
      title: 'Timeline-first V2',
      subtitle: 'Scene 3',
      body: 'The visual model provides realistic content when needed.',
      accent_color: '#22c55e',
      visual_role: 'cta',
    },
  ],
  transitions: [
    {
      id: 'preview_transition_001',
      from_scene_id: 'preview_card_001',
      to_scene_id: 'preview_card_002',
      type: 'fade',
      duration_sec: 0.35,
    },
    {
      id: 'preview_transition_002',
      from_scene_id: 'preview_card_002',
      to_scene_id: 'preview_card_003',
      type: 'light_flash',
      duration_sec: 0.3,
    },
  ],
  overlays: [
    {
      id: 'preview_caption',
      type: 'caption',
      start_sec: 0.4,
      end_sec: 5.6,
      text: 'V2 renders full Remotion timelines now.',
      x_pct: 50,
      y_pct: 86,
      width_pct: 78,
      background: 'rgba(15, 23, 42, 0.68)',
      animation: 'slide_up_fade',
    },
  ],
  material_jobs: [],
  render_policy: {
    renderer: 'remotion_timeline',
    fallback_renderer: 'overlay_compose',
  },
}
