import type { CapabilityPluginManifest } from '../../../types/capability-registry.v1.js'

export const CRYSTAL_LENS_REVEAL_TRANSITION_PLUGIN: CapabilityPluginManifest = {
  id: 'crystal_lens_reveal_transition',
  label: 'Crystal Lens Reveal Transition',
  status: 'verified',
  targetLayer: 'effect',
  layerKind: 'mask_reveal',
  atomicity: 'atomic',
  family: 'crystal_lens_reveal',
  primaryLayer: 'mask_reveal',
  secondaryLayers: [],
  fallbackPreset: 'primitive_mask_reveal',
  capabilities: [
    'image to image transition',
    'next asset reveal',
    'reveal asset through crystal lens',
    'glass refraction transition',
    'circular growing transition',
    'lens wipe between materials',
    'rippling magnified reveal',
    'water surface lens reveal',
  ],
  requiredParams: ['reveal_asset_id'],
  defaultParams: {
    lens_style: 'crystal',
    start_radius_pct: 4,
    mid_radius_pct: 34,
    end_radius_pct: 130,
    x_pct: 50,
    y_pct: 50,
    magnification: 1.12,
    distortion_px: 18,
    wave_strength_px: 16,
    wave_speed: 1.15,
    water_jitter_px: 22,
    water_micro_jitter_px: 5,
    water_band_opacity: 0.22,
    water_caustic_opacity: 0.36,
    rim_width_px: 5,
    glow_px: 34,
    chromatic_px: 4,
  },
  compatibleLayers: ['texture_grade', 'distortion', 'audio_driver'],
  acceptedAssetTypes: ['image', 'video', 'generated_video'],
  negativeKeywords: [
    'triangle collage',
    'split panel layout',
    'single image lens demo',
    'decorative overlay only',
    'text overlay',
  ],
  boundary: {
    supports: {
      'editorial.role': ['transition_between_visual_materials', 'next_asset_reveal'],
      'geometry.mask_shape': ['circle'],
      'mask.motion': ['radial_expand', 'lens_wipe'],
      'style.lens': ['crystal', 'glass_refraction', 'chromatic_edge'],
      'style.distortion': ['animated_turbulence', 'ripple_rings', 'water_surface_wobble'],
    },
    cannotSupport: [
      'geometry.layout=collage',
      'geometry.primitive_sides=3',
      'motion.object=orb',
    ],
    forbiddenLayers: ['layout', 'overlay', 'motion_driver', 'color_transform'],
    requiresCompositionFor: ['texture_grade', 'audio_driver'],
    adaptability: {
      geometry: 'medium',
      timing: 'high',
      style: 'high',
      assets: 'medium',
    },
  },
  description:
    'A circular crystal lens transition between two visual materials. reveal_asset_id or next_asset_id selects the image or video revealed through the expanding refractive lens.',
}
