import type { CapabilityPluginManifest } from '../../../types/capability-registry.v1.js'
import { CRYSTAL_LENS_REVEAL_TRANSITION_PLUGIN } from './crystal-lens-reveal-transition.js'
import { BEAT_COLOR_UNLOCK_REVEAL_PLUGINS } from './beat-color-unlock-reveal.js'

export const MASK_REVEAL_PLUGINS: CapabilityPluginManifest[] = [
  ...BEAT_COLOR_UNLOCK_REVEAL_PLUGINS,
  {
    id: 'circle_mask_reveal',
    label: 'Circle Mask Reveal',
    status: 'verified',
    targetLayer: 'effect',
    layerKind: 'mask_reveal',
    atomicity: 'atomic',
    family: 'geometric_reveal',
    primaryLayer: 'mask_reveal',
    secondaryLayers: [],
    fallbackPreset: 'primitive_mask_reveal',
    capabilities: ['circle mask', 'portal mask', 'radial reveal', 'circular reveal'],
    requiredParams: ['mask.radius_pct_keyframes', 'mask.position_keyframes'],
    defaultParams: {
      mask: { shape: 'circle', beat_reactive_scale: true },
    },
    compatibleLayers: ['color_transform', 'texture_grade', 'motion_driver', 'audio_driver'],
    acceptedAssetTypes: ['image', 'video', 'generated_video'],
    negativeKeywords: ['black white only', 'grayscale only', 'triangle collage'],
    boundary: {
      supports: {
        'geometry.mask_shape': ['circle'],
        'mask.motion': ['expand_from_center', 'radial_expand'],
      },
      cannotSupport: [
        'style.color_transform=grayscale_to_color',
        'motion.object=orb',
        'geometry.layout=collage',
        'geometry.primitive_sides=3',
      ],
      forbiddenLayers: ['color_transform', 'motion_driver', 'layout', 'distortion', 'overlay'],
      requiresCompositionFor: ['color_unlock', 'ring_motion'],
      adaptability: {
        geometry: 'medium',
        timing: 'medium',
        style: 'none',
        assets: 'medium',
      },
    },
    description: 'Atomic circular reveal mask. It exposes only the mask shape/motion, not color transform or ring overlay.',
  },
  {
    id: 'final_burst_reveal',
    label: 'Final Burst Reveal',
    status: 'verified',
    targetLayer: 'effect',
    layerKind: 'mask_reveal',
    atomicity: 'atomic',
    family: 'burst_reveal',
    primaryLayer: 'mask_reveal',
    secondaryLayers: [],
    fallbackPreset: 'primitive_directional_wave_reveal',
    capabilities: ['final burst', 'full screen reveal', 'explosion reveal', 'burst reveal'],
    requiredParams: ['reveal_events'],
    defaultParams: {},
    compatibleLayers: ['texture_grade', 'audio_driver'],
    acceptedAssetTypes: ['image', 'video', 'generated_video'],
    boundary: {
      supports: {
        'mask.motion': ['burst', 'full_screen_reveal'],
        'mask.scope': ['full_frame'],
      },
      cannotSupport: [
        'geometry.layout=collage',
        'geometry.mask_shape=circle',
        'style.color_transform=grayscale_to_color',
      ],
      forbiddenLayers: ['layout', 'color_transform', 'texture_grade', 'color_grade', 'distortion', 'overlay'],
      requiresCompositionFor: ['color_unlock', 'texture_grade'],
      adaptability: {
        geometry: 'low',
        timing: 'medium',
        style: 'low',
        assets: 'medium',
      },
    },
  },
  {
    id: 'directional_wave_reveal',
    label: 'Directional Wave Reveal',
    status: 'verified',
    targetLayer: 'effect',
    layerKind: 'mask_reveal',
    atomicity: 'atomic',
    family: 'wave_reveal',
    primaryLayer: 'mask_reveal',
    secondaryLayers: [],
    fallbackPreset: 'primitive_directional_wave_reveal',
    capabilities: ['directional wave reveal', 'color unlock wave', 'ripple reveal'],
    requiredParams: ['reveal_events'],
    defaultParams: {},
    compatibleLayers: ['color_transform', 'motion_driver', 'audio_driver'],
    acceptedAssetTypes: ['image', 'video', 'generated_video'],
    boundary: {
      supports: {
        'mask.motion': ['directional_wave', 'radial_wave'],
        'mask.scope': ['event_region', 'full_frame'],
      },
      cannotSupport: [
        'geometry.layout=collage',
        'motion.object=orb',
      ],
      forbiddenLayers: ['layout', 'distortion', 'overlay'],
      requiresCompositionFor: ['color_unlock', 'orb_motion'],
      adaptability: {
        geometry: 'medium',
        timing: 'high',
        style: 'low',
        assets: 'medium',
      },
    },
  },
  {
    id: 'layout_window_mask',
    label: 'Layout Window Mask',
    status: 'verified',
    targetLayer: 'effect',
    layerKind: 'mask_reveal',
    atomicity: 'atomic',
    family: 'window_reveal',
    primaryLayer: 'mask_reveal',
    secondaryLayers: [],
    fallbackPreset: 'primitive_slice_reveal',
    capabilities: ['window mask', 'rectangle reveal', 'geometric reveal', 'rectangular window'],
    requiredParams: ['duration_sec', 'slice_count'],
    defaultParams: {
      direction: 'horizontal',
      mode: 'reveal',
      slice_count: 6,
    },
    compatibleLayers: ['texture_grade', 'audio_driver', 'layout'],
    acceptedAssetTypes: ['image', 'video', 'generated_video'],
    boundary: {
      supports: {
        'geometry.mask_shape': ['rectangle', 'strip'],
        'mask.motion': ['wipe', 'slice', 'window_open'],
        'mask.slice_count': { min: 1, max: 12 },
      },
      cannotSupport: [
        'geometry.primitive_sides=3',
        'geometry.mask_shape=circle',
        'style.color_transform=grayscale_to_color',
      ],
      forbiddenLayers: ['layout', 'color_transform', 'texture_grade', 'color_grade', 'motion_driver', 'distortion', 'overlay'],
      requiresCompositionFor: ['collage_layout', 'color_unlock'],
      adaptability: {
        geometry: 'medium',
        timing: 'medium',
        style: 'low',
        assets: 'medium',
      },
    },
  },
  CRYSTAL_LENS_REVEAL_TRANSITION_PLUGIN,
]
