import type { CapabilityPluginManifest } from '../../../types/capability-registry.v1.js'

export const RADIAL_TRIANGLE_PRISM_COLLAGE_PLUGIN: CapabilityPluginManifest = {
  id: 'radial_triangle_prism_collage',
  label: 'Radial Triangle Prism Collage',
  status: 'verified',
  targetLayer: 'effect',
  layerKind: 'layout',
  atomicity: 'atomic',
  family: 'layout_collage',
  primaryLayer: 'layout',
  secondaryLayers: [],
  fallbackPreset: 'primitive_collage_layout',
  capabilities: [
    'triangle collage',
    'radial triangle collage',
    'radial prism collage',
    'radial wedge montage',
    'triangle mosaic collage',
    'three triangle panel collage',
    'four panel fan collage',
    'bottom center radial triangle collage',
    'left to right progressive sector reveal',
    'multi material triangular sectors',
  ],
  requiredParams: ['panels'],
  defaultParams: {
    layout_mode: 'radial_triangle_prism',
    background_filter: 'saturate(1.35) contrast(1.18) brightness(0.78)',
    panel_filter: 'saturate(1.48) contrast(1.2) brightness(0.92)',
    seam_px: 2.2,
    seam_opacity: 0.68,
    chromatic_px: 2,
    entrance_duration_sec: 0.62,
    side_edge_y_pct: 26,
    stagger_sec: 0.2,
  },
  compatibleLayers: ['texture_grade', 'audio_driver', 'mask_reveal'],
  acceptedAssetTypes: ['image', 'video', 'generated_video'],
  negativeKeywords: [
    'circle portal',
    'single circle reveal',
    'single image lens',
    'decorative overlay only',
    'water ripple only',
    'text overlay',
  ],
  boundary: {
    supports: {
      'geometry.primitive': ['triangle'],
      'geometry.primitive_sides': 3,
      'geometry.layout': ['collage', 'radial_fan'],
      'geometry.arrangement': ['radial', 'bottom_center_fan', 'triangle_mosaic'],
      'geometry.arrangement.type': ['radial', 'bottom_center_fan', 'triangle_mosaic'],
      'geometry.panel_count': { min: 3, max: 4 },
      'mask.motion': ['left_to_right_sector_sweep'],
      'style.edge': ['prism_seam', 'chromatic_fringe'],
    },
    cannotSupport: [
      'geometry.mask_shape=circle',
      'style.color_transform=grayscale_to_color',
      'motion.object=orb',
    ],
    forbiddenLayers: ['overlay', 'color_transform', 'motion_driver', 'distortion'],
    requiresCompositionFor: ['texture_grade', 'audio_driver'],
    adaptability: {
      geometry: 'high',
      timing: 'medium',
      style: 'medium',
      assets: 'high',
    },
  },
  description:
    'A three- or four-panel triangular prism collage radiating from the bottom-center origin. Each panel can map to a different asset_id and enters progressively from left to right.',
}
